title: Template for OTS Brussels materials
baseurl: http://opentechschool-brussels.github.io/material-template

markdown: redcarpet
redcarpet:
   extensions: ["no_intra_emphasis", "fenced_code_blocks", "disable_indented_code_blocks", "strikethrough", "autolink"]

pygments: true

permalink: title.html
